
=head1 NAME

App::sqldb_schema - generate a SQL::DB schema from a database

=head1 VERSION

0.19_9. Development release.

=head1 DESCRIPTION

This is the implementation of the L<sqldb-schema> application.

=head1 SEE ALSO

L<sqldb-schema>, L<App::Dispatcher::Tutorial>

=head1 AUTHOR

Mark Lawrence E<lt>nomad@null.netE<gt>

=head1 COPYRIGHT AND LICENSE

Copyright (C) 2011 Mark Lawrence <nomad@null.net>

This program is free software; you can redistribute it and/or modify it
under the terms of the GNU General Public License as published by the
Free Software Foundation; either version 3 of the License, or (at your
option) any later version.

=cut

# vim: set tabstop=4 expandtab:

